### PR TITLE
Closes #27: Address incorrect calculation of micro_seconds on Timespec to_typed_v…

### LINKED ISSUE #27: Microsecond/nanosecond timestamp calculation is probably wrong
See #26.

### PR DESCRIPTION
**Pull request by fluffyemily**
…alue

### CODE REVIEW

File: rust/store/src/lib.rs [hunk 1]
```diff
@@ -120,7 +120,7 @@ impl ToTypedValue for f64 {
 impl ToTypedValue for Timespec {
     fn to_typed_value(&self) -> TypedValue {
         // TODO: shouldn't that be / 1000?!
-        let micro_seconds = (self.sec * 1000000) + i64::from((self.nsec * 1000));
+        let micro_seconds = (self.sec * 1000000) + i64::from((self.nsec / 1000));
```
Comment (rnewman) [inline rust/store/src/lib.rs]: Rust supports `1_000_000`, IIRC. Wise to use it here.

File: rust/store/src/lib.rs [hunk 2]
```diff
@@ -276,3 +276,22 @@ impl Store {
...
+        ToTypedValue,
+        TypedValue,
+        Timespec,
+    };
+
+    #[test]
+    fn test_timespec_to_typed_value() {
+        let timespec = Timespec {
+            sec: 1518434618,
+            nsec: 740993000,
```
Comment (rnewman) [inline rust/store/src/lib.rs]: We have tests for truncation:

https://github.com/mozilla/mentat/commit/ebb77d59bc7aeab94f46efcf70759fbfe2d0830f#diff-b35d96f723d9e1ad4e01cbd9840b2754R737

It would be nice, here, to see a non-`000` `nsec`, so we can see that you're truncating, too.

**Review by rnewman — CHANGES_REQUESTED** [review]

**Review by rnewman — APPROVED** [review]
